version: '3.8'

services:
  
  # Base de datos
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tiendadb
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    volumes:
      - ./database/tienda.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  
  # Administra la base de datos y expone una web en 8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: user_name
      PMA_PASSWORD: user_password
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mysql

# Web server
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./web page:/usr/share/nginx/html
    restart: always
    depends_on:
      - mysql
      - phpmyadmin
