version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tiendadb
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    volumes:
      - ./database/tienda.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: user_name
      PMA_PASSWORD: user_password
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mysql
